#! /usr/bin/env bash

#       Black=$(tput setaf 0)
#     BlackBG=$(tput setab 0)
#    DarkGrey=$(tput bold; tput setaf 0)
#   LightGrey=$(tput setaf 7)
# LightGreyBG=$(tput setab 7)
#       White=$(tput bold; tput setaf 7)
#         Red=$(tput setaf 1)
#       RedBG=$(tput setab 1)
#    LightRed=$(tput bold; tput setaf 1)
#       Green=$(tput setaf 2)
#     GreenBG=$(tput setab 2)
#  LightGreen=$(tput bold; tput setaf 2)
#       Brown=$(tput setaf 3)
#     BrownBG=$(tput setab 3)
#      Yellow=$(tput bold; tput setaf 3)
#        Blue=$(tput setaf 4)
#      BlueBG=$(tput setab 4)
#   LightBlue=$(tput bold; tput setaf 4)
#      Purple=$(tput setaf 5)
#    PurpleBG=$(tput setab 5)
#        Pink=$(tput bold; tput setaf 5)
#        Cyan=$(tput setaf 6)
#      CyanBG=$(tput setab 6)
#   LightCyan=$(tput bold; tput setaf 6)
#        Bold=$(tput bold)
#   Underline=$(tput smul)
#       Reset=$(tput sgr0)

b=$(tput bold)
u=$(tput smul)
r=$(tput sgr0)

# Rows:    0-7 for the fg (eg: tput setaf 3)
# Columns: 0-7 for the bg (eg: tput setab 7), - means default bg

for ((i = 0; i < 8; i++)); do

   fg=$(tput setaf "$i")
   echo -n "$fg$i- $u$i-$r $fg$b$i- $u$i-$r "

   for ((j = 0; j < 8; j++)); do

      bg=$(tput setab "$j")
      echo -n "$fg$bg$i$j $u$i$j$r$fg$bg$b $i$j $u$i$j$r$bg $r"
   done
   echo
done

echo
set -- "${1:-0-}" "${2:-77}" "${@:3}"

for lc in "$@"; do
                      fg=$(tput setaf "${lc%?}")
   [[ $lc != *- ]] && bg=$(tput setab "${lc#?}") || unset bg
   echo "$lc: $fg${bg}Lorem ipsum dolor ${u}sit amet, consectetur$r$fg$bg$b"\
        "adipisicing elit, ${u}sed do eiusmod!$r"
done
