#! /usr/bin/env bash

# eix-sync
emerge --sync
eix-update

# -vauND
if emerge --verbose --ask --update --newuse --deep --with-bdeps=y world; then
   emerge --depclean # (-c)
   revdep-rebuild
fi

if [[ $1 == '-a' ]]; then
   eclean -i distfiles
   if emaint --check world; then
      emaint --fix   world
   fi
fi
