#! /usr/bin/env bash

# Will add a host to my ssh config file and link it in ~/bin -> mssh
# madd-host {host} {ip}

mkhost() {
   ln -s "$HOME"/bin/{mssh,"$1"}

   if ! command grep -qi "$1" "$HOME"/.ssh/config; then
      printf 'host %s\n   hostname %s\n' "$1" "$2" >> "$HOME"/.ssh/config
      # printf '%s %s\n' "$2" "$1" >> "$HOME"/.hosts
      # sudo bash -c 'printf '%s %s\n' "$2" "$1" >> /etc/hosts' "$0" "$@"
   else
      return 1
   fi
}

# Reading a file with 'host ip' entries
# madd-host {myfile}
# todo: read in an array in order to avoid multiple greps, lns ...?
if (($# == 1)); then

   unset added
   while read -r host ip; do
      if [[ $host != \#* ]]; then
         mkhost "$host" "$ip" && added=true
      fi
   done < "$1"

   # edit ssh config's last line
   [[ $added ]] && vim -c 'silent $' "$HOME"/.ssh/config
   # command vim -nNX -u NONE -c 'silent bufdo$' "$HOME"/.{ssh/config,hosts}

# Adding a single host
# madd-host {host} {ip}
elif (($# == 2)); then
   mkhost "$1" "$2" && vim -c 'silent $' "$HOME"/.ssh/config
fi
