#! /usr/bin/env bash

mkrepos() {

   [[ ! -d $HOME/config ]] && mkdir -p "$HOME"/config

   cd "$HOME"/config

   git clone git@github.com:kurkale6ka/bashfiles.git
   git clone git@github.com:kurkale6ka/help.git

   if git clone git@github.com:kurkale6ka/vimfiles.git; then

      cd vimfiles/bundle

      git clone git@github.com:kurkale6ka/vim-blanklines.git
      git clone git@github.com:kurkale6ka/vim-blockinsert.git
      git clone git@github.com:kurkale6ka/vim-quotes.git
      git clone git@github.com:kurkale6ka/vim-sequence.git
      git clone git@github.com:kurkale6ka/vim-swap.git
      git clone git://github.com/godlygeek/csapprox.git
      git clone git://github.com/godlygeek/tabular.git
      git clone git://github.com/tpope/vim-pathogen.git
      git clone git://github.com/tpope/vim-abolish.git
      git clone git://github.com/tpope/vim-endwise.git
      git clone git://github.com/tpope/vim-unimpaired.git
      git clone git://github.com/tpope/vim-surround.git
      git clone git://github.com/tpope/vim-repeat.git
      git clone git://github.com/tpope/vim-ragtag.git
      git clone git://github.com/tpope/vim-flatfoot.git
      git clone git://github.com/scrooloose/nerdcommenter.git
      git clone git://github.com/vim-scripts/MarkLines.git
      git clone git://github.com/vim-scripts/bufkill.vim.git
      # git clone git://github.com/vim-scripts/L9.git
      # git clone git://github.com/vim-scripts/FuzzyFinder.git
      # git clone git://github.com/vim-scripts/YankRing.vim.git
      # git clone git://github.com/ervandew/supertab.git
      # git clone git://github.com/spiiph/vim-space.git
   fi
}

mkr() {

   [[ ! -d $HOME/config ]] && mkdir -p "$HOME"/config

   cd "$HOME"/config

   git clone git@github.com:kurkale6ka/bashfiles.git
   git clone git@github.com:kurkale6ka/vimfiles.git
}

updaterepos() {

   cd "$HOME"/config/bashfiles
   git pull git@github.com:kurkale6ka/bashfiles.git master

   cd "$HOME"/config/help
   git pull git@github.com:kurkale6ka/help.git master

   cd "$HOME"/config/vimfiles
   git pull git@github.com:kurkale6ka/vimfiles.git master

   cd "$HOME"/config/vimfiles/bundle/vim-blanklines
   git pull git@github.com:kurkale6ka/vim-blanklines.git master

   cd "$HOME"/config/vimfiles/bundle/vim-blockinsert
   git pull git@github.com:kurkale6ka/vim-blockinsert.git master

   cd "$HOME"/config/vimfiles/bundle/vim-quotes
   git pull git@github.com:kurkale6ka/vim-quotes.git master

   cd "$HOME"/config/vimfiles/bundle/vim-sequence
   git pull git@github.com:kurkale6ka/vim-sequence.git master

   cd "$HOME"/config/vimfiles/bundle/vim-swap
   git pull git@github.com:kurkale6ka/vim-swap.git master

   cd "$HOME"/config/vimfiles/bundle/csapprox
   git pull git://github.com/godlygeek/csapprox.git master

   cd "$HOME"/config/vimfiles/bundle/tabular
   git pull git://github.com/godlygeek/tabular.git master

   cd "$HOME"/config/vimfiles/bundle/vim-pathogen
   git pull git://github.com/tpope/vim-pathogen.git master

   cd "$HOME"/config/vimfiles/bundle/vim-abolish
   git pull git://github.com/tpope/vim-abolish.git master

   cd "$HOME"/config/vimfiles/bundle/vim-endwise
   git pull git://github.com/tpope/vim-endwise.git master

   cd "$HOME"/config/vimfiles/bundle/vim-unimpaired
   git pull git://github.com/tpope/vim-unimpaired.git master

   cd "$HOME"/config/vimfiles/bundle/vim-surround
   git pull git://github.com/tpope/vim-surround.git master

   cd "$HOME"/config/vimfiles/bundle/vim-repeat
   git pull git://github.com/tpope/vim-repeat.git master

   cd "$HOME"/config/vimfiles/bundle/vim-ragtag
   git pull git://github.com/tpope/vim-ragtag.git master

   cd "$HOME"/config/vimfiles/bundle/vim-flatfoot
   git pull git://github.com/tpope/vim-flatfoot.git master

   cd "$HOME"/config/vimfiles/bundle/nerdcommenter
   git pull git://github.com/scrooloose/nerdcommenter.git master

   cd "$HOME"/config/vimfiles/bundle/MarkLines
   git pull git://github.com/vim-scripts/MarkLines.git master

   cd "$HOME"/config/vimfiles/bundle/bufkill.vim
   git pull git://github.com/vim-scripts/bufkill.vim.git master

   # cd "$HOME"/config/vimfiles/bundle/L9
   # git pull git://github.com/vim-scripts/L9.git master

   # cd "$HOME"/config/vimfiles/bundle/FuzzyFinder
   # git pull git://github.com/vim-scripts/FuzzyFinder.git master

   # cd "$HOME"/config/vimfiles/bundle/YankRing.vim
   # git pull git://github.com/vim-scripts/YankRing.vim.git master

   # cd "$HOME"/config/vimfiles/bundle/supertab
   # git pull git://github.com/ervandew/supertab.git master

   # cd "$HOME"/config/vimfiles/bundle/vim-space
   # git pull git://github.com/spiiph/vim-space.git master
}

updater() {

   cd "$HOME"/config/bashfiles
   git pull git@github.com:kurkale6ka/bashfiles.git master

   cd "$HOME"/config/vimfiles
   git pull git@github.com:kurkale6ka/vimfiles.git master
}

cprepos() {

   wget --no-check-certificate https://github.com/kurkale6ka/bashfiles/tarball/master
   wget --no-check-certificate https://github.com/kurkale6ka/help/tarball/master

   if wget --no-check-certificate https://github.com/kurkale6ka/vimfiles/tarball/master; then

      wget --no-check-certificate https://github.com/kurkale6ka/vim-blanklines/tarball/master
      wget --no-check-certificate https://github.com/kurkale6ka/vim-blockinsert/tarball/master
      wget --no-check-certificate https://github.com/kurkale6ka/vim-quotes/tarball/master
      wget --no-check-certificate https://github.com/kurkale6ka/vim-sequence/tarball/master
      wget --no-check-certificate https://github.com/kurkale6ka/vim-swap/tarball/master
      wget --no-check-certificate https://github.com/godlygeek/csapprox/tarball/master
      wget --no-check-certificate https://github.com/godlygeek/tabular/tarball/master
      wget --no-check-certificate https://github.com/tpope/vim-pathogen/tarball/master
      wget --no-check-certificate https://github.com/tpope/vim-abolish/tarball/master
      wget --no-check-certificate https://github.com/tpope/vim-endwise/tarball/master
      wget --no-check-certificate https://github.com/tpope/vim-unimpaired/tarball/master
      wget --no-check-certificate https://github.com/tpope/vim-surround/tarball/master
      wget --no-check-certificate https://github.com/tpope/vim-repeat/tarball/master
      wget --no-check-certificate https://github.com/tpope/vim-ragtag/tarball/master
      wget --no-check-certificate https://github.com/tpope/vim-flatfoot/tarball/master
      wget --no-check-certificate https://github.com/scrooloose/nerdcommenter/tarball/master
      wget --no-check-certificate https://github.com/vim-scripts/MarkLines/tarball/master
      wget --no-check-certificate https://github.com/vim-scripts/bufkill.vim/tarball/master
      # wget --no-check-certificate https://github.com/vim-scripts/L9/tarball/master
      # wget --no-check-certificate https://github.com/vim-scripts/FuzzyFinder/tarball/master
      # wget --no-check-certificate https://github.com/vim-scripts/YankRing.vim/tarball/master
      # wget --no-check-certificate https://github.com/ervandew/supertab/tarball/master
      # wget --no-check-certificate https://github.com/spiiph/vim-space/tarball/master
   fi

   local repo
   for repo in master*; do
      tar zxvf "$repo" # -C <dir>
      rm "$repo"
   done
}

mklinks() {

   ln -sT "$HOME"/config/vimfiles                   "$HOME"/.vim
   ln -s  "$HOME"/config/vimfiles/.vimrc            "$HOME"
   ln -s  "$HOME"/config/vimfiles/.gvimrc           "$HOME"

   if ((! $#)); then
      ln -s "$HOME"/config/vimfiles/bundle/vim-pathogen/autoload/pathogen.vim\
            "$HOME"/config/vimfiles/autoload
   fi

   ln -s  "$HOME"/config/bashfiles/.profile         "$HOME"
   ln -s  "$HOME"/config/bashfiles/.bash_profile    "$HOME"
   ln -s  "$HOME"/config/bashfiles/.bash_login      "$HOME"
   ln -s  "$HOME"/config/bashfiles/.bashrc          "$HOME"
   ln -s  "$HOME"/config/bashfiles/.bashrc_after    "$HOME"
   ln -s  "$HOME"/config/bashfiles/.logout          "$HOME"
   ln -s  "$HOME"/config/bashfiles/.bash_logout     "$HOME"
   ln -s  "$HOME"/config/bashfiles/.inputrc         "$HOME"
   ln -s  "$HOME"/config/bashfiles/.irbrc           "$HOME"

   ln -s  "$HOME"/config/help/.gitignore            "$HOME"
   ln -s  "$HOME"/config/help/.screenrc             "$HOME"
   ln -s  "$HOME"/config/help/.curlrc               "$HOME"
   ln -s  "$HOME"/config/help/.toprc                "$HOME"
   ln -s  "$HOME"/config/help/.my.cnf               "$HOME"
   ln -sT "$HOME"/config/help/.irssi                "$HOME"/.irssi

   ln -sT "$HOME"/config/vimfiles                   "$HOME"/vimfiles
   ln -sT "$HOME"/config/bashfiles                  "$HOME"/bashfiles
   ln -sT "$HOME"/config/help                       "$HOME"/help

   [[ ! -d $HOME/bin ]] && mkdir -p "$HOME"/bin

   ln -s  "$HOME"/config/bashfiles/scripts/mkconfig "$HOME"/bin
   ln -s  "$HOME"/config/vimfiles/scripts/vimcat    "$HOME"/bin/vc
}

rmlinks() {

   rm    "$HOME"/.vim
   rm    "$HOME"/.vimrc
   rm    "$HOME"/.gvimrc
   rm    "$HOME"/config/vimfiles/autoload/pathogen.vim
   rm    "$HOME"/.profile
   rm    "$HOME"/.bash_profile
   rm    "$HOME"/.bash_login
   rm    "$HOME"/.bashrc
   rm    "$HOME"/.bashrc_after
   rm    "$HOME"/.logout
   rm    "$HOME"/.bash_logout
   rm    "$HOME"/.inputrc
   rm    "$HOME"/.irbrc
   rm    "$HOME"/.gitignore
   rm    "$HOME"/.screenrc
   rm    "$HOME"/.curlrc
   rm    "$HOME"/.toprc
   rm    "$HOME"/.my.cnf
   rm -r "$HOME"/.irssi
   rm    "$HOME"/vimfiles
   rm    "$HOME"/bashfiles
   rm    "$HOME"/help
   rm    "$HOME"/bin/mkconfig
   rm    "$HOME"/bin/vc
}

options[0]='Update repositories'
options[1]='Create repositories'
options[2]='Copy repositories'
options[3]='Update bashfiles and vimfiles'
options[4]='Create bashfiles and vimfiles'
options[5]='Make links'
options[6]='Remove links'

select choice in "${options[@]}"
do
   case "$choice" in
      "${options[0]}") updaterepos; break;;
      "${options[1]}") mkrepos;     break;;
      "${options[2]}") cprepos;     break;;
      "${options[3]}") updater;     break;;
      "${options[4]}") mkr;         break;;
      "${options[5]}") mklinks;     break;;
      "${options[6]}") rmlinks;     break;;
                    *) echo '*** Wrong choice ***' >&2
   esac
done
