#! /usr/bin/env bash

mkrepos() {

   mkdir -p "$HOME"/config
   cd       "$HOME"/config || exit 1

   if [[ ! -d bashfiles ]]
   then git clone git@github.com:kurkale6ka/bashfiles.git
   fi
   if [[ ! -d help ]]
   then git clone git@github.com:kurkale6ka/help.git
   fi
   if [[ ! -d vimfiles ]]
   then git clone git@github.com:kurkale6ka/vimfiles.git
   fi

   cd vimfiles/bundle || exit 1

   if [[ ! -d vim-blanklines ]]
   then git clone git@github.com:kurkale6ka/vim-blanklines.git
   fi
   if [[ ! -d vim-blockinsert ]]
   then git clone git@github.com:kurkale6ka/vim-blockinsert.git
   fi
   if [[ ! -d vim-quotes ]]
   then git clone git@github.com:kurkale6ka/vim-quotes.git
   fi
   if [[ ! -d vim-sequence ]]
   then git clone git@github.com:kurkale6ka/vim-sequence.git
   fi
   if [[ ! -d vim-swap ]]
   then git clone git@github.com:kurkale6ka/vim-swap.git
   fi
   if [[ ! -d csapprox ]]
   then git clone git://github.com/godlygeek/csapprox.git
   fi
   if [[ ! -d tabular ]]
   then git clone git://github.com/godlygeek/tabular.git
   fi
   if [[ ! -d vim-pathogen ]]
   then git clone git://github.com/tpope/vim-pathogen.git
   fi
   if [[ ! -d vim-abolish ]]
   then git clone git://github.com/tpope/vim-abolish.git
   fi
   if [[ ! -d vim-endwise ]]
   then git clone git://github.com/tpope/vim-endwise.git
   fi
   if [[ ! -d vim-unimpaired ]]
   then git clone git://github.com/tpope/vim-unimpaired.git
   fi
   if [[ ! -d vim-surround ]]
   then git clone git://github.com/tpope/vim-surround.git
   fi
   if [[ ! -d vim-repeat ]]
   then git clone git://github.com/tpope/vim-repeat.git
   fi
   if [[ ! -d vim-ragtag ]]
   then git clone git://github.com/tpope/vim-ragtag.git
   fi
   if [[ ! -d vim-flatfoot ]]
   then git clone git://github.com/tpope/vim-flatfoot.git
   fi
   if [[ ! -d nerdcommenter ]]
   then git clone git://github.com/scrooloose/nerdcommenter.git
   fi
   if [[ ! -d MarkLines ]]
   then git clone git://github.com/vim-scripts/MarkLines.git
   fi
   if [[ ! -d bufkill.vim ]]
   then git clone git://github.com/vim-scripts/bufkill.vim.git
   fi
   if [[ ! -d vim-puppet ]]
   then git clone git://github.com/rodjek/vim-puppet.git
   fi
   if [[ ! -d UltiSnips ]]
   then git clone git://github.com/vim-scripts/UltiSnips.git
   fi
}

updaterepos() {

   cd "$HOME"/config || exit 1

   if cd bashfiles
   then git pull git@github.com:kurkale6ka/bashfiles.git master
   fi

   if cd help
   then git pull git@github.com:kurkale6ka/help.git master
   fi

   if cd vimfiles
   then git pull git@github.com:kurkale6ka/vimfiles.git master
   fi

   cd vimfiles/bundle || exit 1

   if cd vim-blanklines
   then git pull git@github.com:kurkale6ka/vim-blanklines.git master
   fi

   if cd vim-blockinsert
   then git pull git@github.com:kurkale6ka/vim-blockinsert.git master
   fi

   if cd vim-quotes
   then git pull git@github.com:kurkale6ka/vim-quotes.git master
   fi

   if cd vim-sequence
   then git pull git@github.com:kurkale6ka/vim-sequence.git master
   fi

   if cd vim-swap
   then git pull git@github.com:kurkale6ka/vim-swap.git master
   fi

   if cd csapprox
   then git pull git://github.com/godlygeek/csapprox.git master
   fi

   if cd tabular
   then git pull git://github.com/godlygeek/tabular.git master
   fi

   if cd vim-pathogen
   then git pull git://github.com/tpope/vim-pathogen.git master
   fi

   if cd vim-abolish
   then git pull git://github.com/tpope/vim-abolish.git master
   fi

   if cd vim-endwise
   then git pull git://github.com/tpope/vim-endwise.git master
   fi

   if cd vim-unimpaired
   then git pull git://github.com/tpope/vim-unimpaired.git master
   fi

   if cd vim-surround
   then git pull git://github.com/tpope/vim-surround.git master
   fi

   if cd vim-repeat
   then git pull git://github.com/tpope/vim-repeat.git master
   fi

   if cd vim-ragtag
   then git pull git://github.com/tpope/vim-ragtag.git master
   fi

   if cd vim-flatfoot
   then git pull git://github.com/tpope/vim-flatfoot.git master
   fi

   if cd nerdcommenter
   then git pull git://github.com/scrooloose/nerdcommenter.git master
   fi

   if cd MarkLines
   then git pull git://github.com/vim-scripts/MarkLines.git master
   fi

   if cd bufkill.vim
   then git pull git://github.com/vim-scripts/bufkill.vim.git master
   fi

   if cd vim-puppet
   then git pull git://github.com/rodjek/vim-puppet.git master
   fi

   if cd UltiSnips
   then git pull git://github.com/vim-scripts/UltiSnips.git master
   fi
}

cprepos() {
   wget --no-check-certificate                               \
      https://github.com/kurkale6ka/bashfiles/tarball/master \
      https://github.com/kurkale6ka/help/tarball/master

   if wget --no-check-certificate \
      https://github.com/kurkale6ka/vimfiles/tarball/master
   then
      wget --no-check-certificate                                     \
         https://github.com/kurkale6ka/vim-blanklines/tarball/master  \
         https://github.com/kurkale6ka/vim-blockinsert/tarball/master \
         https://github.com/kurkale6ka/vim-quotes/tarball/master      \
         https://github.com/kurkale6ka/vim-sequence/tarball/master    \
         https://github.com/kurkale6ka/vim-swap/tarball/master        \
         https://github.com/godlygeek/csapprox/tarball/master         \
         https://github.com/godlygeek/tabular/tarball/master          \
         https://github.com/tpope/vim-pathogen/tarball/master         \
         https://github.com/tpope/vim-abolish/tarball/master          \
         https://github.com/tpope/vim-endwise/tarball/master          \
         https://github.com/tpope/vim-unimpaired/tarball/master       \
         https://github.com/tpope/vim-surround/tarball/master         \
         https://github.com/tpope/vim-repeat/tarball/master           \
         https://github.com/tpope/vim-ragtag/tarball/master           \
         https://github.com/tpope/vim-flatfoot/tarball/master         \
         https://github.com/scrooloose/nerdcommenter/tarball/master   \
         https://github.com/vim-scripts/MarkLines/tarball/master      \
         https://github.com/vim-scripts/bufkill.vim/tarball/master    \
         https://github.com/rodjek/vim-puppet/tarball/master          \
         https://github.com/vim-scripts/UltiSnips/tarball/master
   fi
   local repo
   for repo in master*; do
      # Use tar with -C <dir> ...?
      tar zxvf "$repo" && command rm "$repo"
   done
}

 rcdirs=({bash,vim}files help)
    rcs=(.gitignore .my.cnf .{curl,input,irb,screen,top}rc)
 vimrcs=(.{,g}vimrc)
bashrcs=(.profile .bash_{profile,login,logout} .bashrc .logout)
 bashxs=(colors em mkconfig madd-host mssh)

mklinks() {

   # Same as in ${parameter#word to remove} or ${parameter%word to remove},
   # # <=> \< and % <=> \>, so ${rcdir/#/$HOME/config/} means replace the
   # beginning of rcdir with $HOME/config/
   local rcdir
   for rcdir in "${rcdirs[@]}"
   do ln -sT "${rcdir/#/$HOME/config/}" "${rcdir/#/$HOME/}"
   done

   ln -sT "$HOME"/config/vimfiles "$HOME"/.vim

   if ((! $#)); then
      ln -s "$HOME"/config/vimfiles/bundle/vim-pathogen/autoload/pathogen.vim \
            "$HOME"/config/vimfiles/autoload
   fi

   ln -s "${rcs[@]/#/$HOME/config/help/}"      \
      "${vimrcs[@]/#/$HOME/config/vimfiles/}"  \
     "${bashrcs[@]/#/$HOME/config/bashfiles/}" "$HOME"

   mkdir -p "$HOME"/bin
   if [[ -d $HOME/bin ]]; then
      ln -s "${bashxs[@]/#/$HOME/config/bashfiles/scripts/}" \
            "$HOME"/config/vimfiles/scripts/vc               "$HOME"/bin
   fi
}

rmlinks() {
   command \
      rm "$HOME"/{.vim,config/vimfiles/autoload/pathogen.vim,bin/vc} \
                  "${rcdirs[@]/#/$HOME/}"                            \
                     "${rcs[@]/#/$HOME/}"                            \
                  "${vimrcs[@]/#/$HOME/}"                            \
                 "${bashrcs[@]/#/$HOME/}"                            \
                  "${bashxs[@]/#/$HOME/bin/}"
}

mkenv() {
   mkrepos

   # Put in @sets ?
   emerge bind-tools     \
          evince         \
          figlet         \
          gcalctool      \
          # dev-vcs/git -gtk
          git            \
          gnupg          \
          moreutils      \
          ntp            \
          # sys-process/parallel \ ?
          sudo           \
          tcpdump        \
          vixie-cron     \
          wgetpaste      \
          x11-misc/xclip
   # rc-update add ntpd vixie-cron default

   # visudo
   # Defaults:mitko timestamp_timeout=50 # min before asking for password again

   mkdir -p "$HOME"/backups
   # crontab -u "$USER" "$HOME"/help/crontab.backups
}

 options=('Update repositories' 'Create repositories' 'Copy repositories')
options+=('Make links'          'Remove links'        'Machine setup')

select choice in "${options[@]}"
do
   case "$choice" in
      "${options[0]}") updaterepos; break;;
      "${options[1]}") mkrepos;     break;;
      "${options[2]}") cprepos;     break;;
      "${options[3]}") mklinks;     break;;
      "${options[4]}") rmlinks;     break;;
      "${options[5]}") mkenv;       break;;
                    *) echo '*** Wrong choice ***' >&2
   esac
done
