#! /usr/bin/env bash

# A script for making sure that all our code is covered by Unit Testing
# except for abstract Classes
#
# Author Dimitar Dimitrov <mitkofr@yahoo.fr>
# ---------------------------------------------------------------------

shopt -s extglob

blue=$(tput setaf 4)
bold=$(tput bold)
reset=$(tput sgr0)

# Print a message to stderr
warn() { echo "$@" >&2; }

if [[ 1 < $# || 1 == $# && $1 != @(-p|--platform) ]]; then

    warn "Usage: ${0##*/} [-p|--platform]"

else

    ext=.php

    project=cbbc

    if (( 1 == $# )); then

        webapp='.'
    else
        workspace=workspace
        webapp="$workspace/$project/webapp"
    fi

    lib="$webapp/.../Models"
    libTest="$webapp/...-test/Models"

    libTestArray=("$libTest"/*Test"$ext" "$libTest"/*/*Test"$ext")
    lTestArray="${libTestArray[@]##*/}"

    controllers="$webapp/.../controllers"
    controllersTest="$webapp/...-test/controllers"

    controllersTestArray=("$controllersTest"/*Test"$ext")
    ctrlTestArray="${controllersTestArray[@]##*/}"

    isIn() {

        local pattern="$1"
        local element

        shift

        for element in "$@"; do

            [[ $element == $pattern ]] && return 0
        done

        return 1
    }

    printf "Files not covered by Unit Testing\n\n"
    printf "$bold$blue$controllers:$reset\n\n"

    for c in "$controllers"/*"$ext"; do

        ctrl="${c##*/}"

        if ! isIn "$ctrl" "${ctrlTestArray[@]//Test$ext/$ext}"; then

            if ! $(grep -iEq '^[[:space:]]*abstract[[:space:]]+class' "$c"); then

                echo "$ctrl"
            fi
        fi
    done

    printf "\n$bold$blue$lib:$reset\n\n"

    for f in "$lib"/*"$ext" "$lib"/*/*"$ext"; do

        file="${f##*/}"

        if ! isIn "$file" "${lTestArray[@]//Test$ext/$ext}"; then

            if ! $(grep -iEq '^[[:space:]]*abstract[[:space:]]+class' "$f"); then

                echo "$file"
            fi
        fi
    done

fi
