#! /usr/bin/env bash

# A script for making sure that all our code is covered by Unit Testing
# except for abstract Classes
#
# Author Dimitar Dimitrov <dimitar.dimitrov@bbc.co.uk>
# ---------------------------------------------------------------------

blue=$(tput setaf 4)
bold=$(tput bold)
reset=$(tput sgr0)

# Print a message to stderr
warn() { echo "$@" >&2; }

if (( 0 < $# )); then

    warn "Usage: ${0##*/}"

else

    ext=.php

    project=org

    lib="/mnt/.../$project/Models"
    libTest="/mnt/...-test/$project/Models"

    libTestArray=("$libTest"/*Test"$ext" "$libTest"/*/*Test"$ext")
    lTestArray="${libTestArray[@]##*/}"

    controllers="/mnt/.../$project/controllers"
    controllersTest="/mnt/...-test/$project/controllers"

    controllersTestArray=("$controllersTest"/*Test"$ext")
    ctrlTestArray="${controllersTestArray[@]##*/}"

    isIn() {

        local pattern="$1"
        local element

        shift

        for element in "$@"; do

            [[ $element == $pattern ]] && return 0
        done

        return 1
    }

    printf "Files not covered by Unit Testing\n\n"
    printf "$bold$blue$controllers:$reset\n\n"

    for c in "$controllers"/*"$ext"; do

        ctrl="${c##*/}"

        if ! isIn "$ctrl" "${ctrlTestArray[@]//Test$ext/$ext}"; then

            if ! $(grep -iEq '^[[:space:]]*abstract[[:space:]]+class' "$c"); then

                echo "$ctrl"
            fi
        fi
    done

    printf "\n$bold$blue$lib:$reset\n\n"

    for f in "$lib"/*"$ext" "$lib"/*/*"$ext"; do

        file="${f##*/}"

        if ! isIn "$file" "${lTestArray[@]//Test$ext/$ext}"; then

            if ! $(grep -iEq '^[[:space:]]*abstract[[:space:]]+class' "$f"); then

                echo "$file"
            fi
        fi
    done

fi
